import type { Metadata } from 'next';
import { inter, raleway } from './fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" className={raleway.variable + ' ' + inter.variable}>
      <body>{children}</body>
    </html>
  );
}
