import CtaContactUs from '@/components/ctaContactUs';
import Navbar from '@/components/navbar/navbar';
import type { Metadata } from 'next';
import { inter, raleway } from './fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" className={raleway.variable + ' ' + inter.variable}>
      <body>
        <Navbar />
        <main className="w-full py-40">{children}</main>
        <footer className="w-full">
          <CtaContactUs />
        </footer>
      </body>
    </html>
  );
}
